version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.0.1-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
      - run: sudo apt-get install libmagickwand-dev
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Webpack の実行
          command: bundle exec rails webpacker:compile
      - run:
          name: データベースのセットアップ
          command: bundle exec rails db:setup
      - run:
          name: データベースのセットアップ
          command: bundle exec rails test:all

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - test:
          requires:
            - build
